# Dockerfile.dashboard
FROM python:3.10-slim

WORKDIR /app

COPY . /app
RUN pip install --upgrade pip
RUN pip install streamlit pandas requests altair nltk certifi

# Download stopwords
RUN python -m nltk.downloader stopwords

EXPOSE 8501
CMD ["streamlit", "run", "dashboard/app.py"]
