# Dockerfile.api
FROM python:3.10-slim

WORKDIR /app

COPY . /app
RUN pip install --upgrade pip
RUN pip install fastapi uvicorn praw nltk certifi

# Download NLTK data
RUN python -m nltk.downloader vader_lexicon

EXPOSE 8000
CMD ["uvicorn", "api.sentiment_api:app", "--host", "0.0.0.0", "--port", "8000"]
