services:
  - type: web
    name: sentilytics-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.sentiment_api:app --host 0.0.0.0 --port 8000
    envVars:
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USER_AGENT
        sync: false

  - type: web
    name: sentilytics-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard/app.py --server.port 10000
    envVars:
      - key: API_URL
        value: https://sentilytics-api.onrender.com/analyze
